### ISSUE TITLE
Annoying first 3 lines when importing

### ISSUE THREAD

**Issue by scary987** [Snowcola/runterra#6]
I always get these 3 debug lines printed when importing your Deck library. For example:
```
True
/home/scary__/LOR Simulator
False
...
```
Would you please so kind to fix that ? Thanks alot.

**Comment by Snowcola** [comment]
Please provide the code you are using to import.

**Comment by scary987** [comment]
from twisted_fate import Deck,Card

**Comment by scary987** [comment]
```
scary__@antonia-ms7713:~/LoR Simulator$ python3
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from twisted_fate import Deck
True
/home/scary__/LoR Simulator
False
>>> 

```
Another Debug output

**Comment by scary987** [comment]
Also noteworthy, that I used the standard pip install

**Comment by Snowcola** [comment]
I merged your fix, and will update the pip package shortly.
